### ISSUE TITLE
Publish draft versions?

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_website#12]
I think there is need for partners and others to review draft versions of Core and SXL. How do we publish them?

**Comment by emiltin** [comment]
I guess a PDF of online format is not optimal since you cannot see what changed. 
A pull request with a diff might be better, if the format is readable?

**Comment by emiltin** [comment]
But if we use a pull request, we could use GitHub Actions to build e.g. a PDF.

**Comment by emiltin** [comment]
Is the Sphinx online version currently build manually from the source?

**Comment by otterdahl** [comment]
> Is the Sphinx online version currently build manually from the source?

Yes. But it is easy to automate

**Comment by emiltin** [comment]
a challenge is that there's isn't a straight-forward way to deploy a draft on github pages.
an alternative would be to simply let people read the RST on GitHub (not the source, but as github renders them), e.g. https://github.com/rsmp-nordic/rsmp_core/blob/master/source/applicability/sxl.rst

**Comment by otterdahl** [comment]
Beyond PDF; sphinx can output to a number of formats, including a single HTML page and compiled HTML pages using various formats. This is also a possibility.

But as you say, it is no real way of publishing a complete draft of the web site using GitHub pages.

**Comment by emiltin** [comment]
The rsmp_schemer repo uses git submodules to check out each version of both core and sxl schemas.

We could do something similar for the core and sxl specs: create a new repo that checks out current, previous and draft versions, then builds using sphinx and deploys via github pages a a single site, with subfolders for each version. the front page could be a index to the various versions.

**Comment by emiltin** [comment]
with that approach we could remove the sphinx libs from the core and sxl, specs repos (where it's duplicated anyways), and instead keep it in the publishing repo.

**Comment by emiltin** [comment]
a variation would be to use github actions to build drafts (pull request) to a sub folders, then commit to a gh-pagers branch. for rsmp_validator i sset up auomatic YARD generation and commiting to the gh-pages branch

**Comment by otterdahl** [comment]
I like your first suggestion. It would separate the source repository with the repository used for publishing. It makes the diffs clearer. I also like the idea to publish past, present and draft versions of the web (online) version.

**Comment by otterdahl** [comment]
I propose that we create a new repo named "rsmp_documentation" which can contain the historical, current as well as draft versions of Core and SXL to be published as a web site. They can be automatically be updated whenever there is a push to "rsmp_core" or "rsmp_sxl_traffic_lights"

**Comment by otterdahl** [comment]
As I test I've created the [rsmp_documentation](https://github.com/rsmp-nordic/rsmp_documentation) repo. It publishes the draft versions of [core](http://rsmp-nordic.org/rsmp_documentation/core/) and [TLC SXL](http://rsmp-nordic.org/rsmp_documentation/rsmp_sxl_traffic_lights/). The documentation is updated using a GitHub runner - but at the moment there is no cross-repo-dispatches.

**Comment by emiltin** [comment]
please confirm the invitation i send you last week

**Comment by otterdahl** [comment]
> please confirm the invitation i send you last week

Not sure what invitation you mean? Perhaps you intended to reply @GunnarRolander in this PR https://github.com/rsmp-nordic/rsmp_validator/pull/110 ?

**Comment by emiltin** [comment]
> > please confirm the invitation i send you last week
> 
> Not sure what invitation you mean? Perhaps you intended to reply @GunnarRolander in this PR [rsmp-nordic/rsmp_validator#110](https://github.com/rsmp-nordic/rsmp_validator/pull/110) ?

you're righ
