### ISSUE TITLE
link to test runs

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_website#37]
It's possible to link to a page with the latest tests runs for each device:

| Device | Test Runs | Note |
|--|--|--|
| [![Gem TLC](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/gem_tlc.yml/badge.svg?branch=master&event=push)](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/gem_tlc.yml) | [View runs](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/gem_tlc.yml?query=branch%3Amaster) | TLC emulator from RSMP Nordic |
| [![Dynniq EC-2](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/dynniq_ec2.yml/badge.svg?event=schedule)](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/dynniq_ec2.yml) | [View runs](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/dynniq_ec2.yml?query=event%3Aschedule) | Physical device |
| [![Swarco ITC-2](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc2.yml/badge.svg?event=schedule)](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc2.yml) | [View runs](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc2.yml?query=event%3Aschedule) | Software simulator |
| [![Swarco ITC-3](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc3.yml/badge.svg?event=schedule)](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc3.yml) | [View runs](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc3.yml?query=event%3Aschedule) | Physical device |

You can link to a page with filter set, e.g. event=schedule, branch=master. This mean we will only show the nightly test runs, not runs caused by PRs etc.

**Comment by emiltin** [comment]
I wish there was a way to link to subpages of the latest runs, to show the actual results, but alas, i didn't find a way to to that from markdown (you can do it with their API of course, but that requires javascript or a server side solution, i think).

a workaround might be to extract the results in a workflow, them commit then to the gh-pages branch so they are published by github pages as part of our site. but then they would be static, and the site would need to be rebuild nightly.

**Comment by otterdahl** [comment]
> I wish there was a way to link to subpages of the latest runs, to show the actual results,

It is worth noting that no actual results are shown unless you are logged in to github. There might be some setting controlling the visibility of test runs.

**Comment by emiltin** [comment]
Actually anyone can view the tests runs and the logs, you just have to be signed into GitHub.
For example, here's a random repo, and I can view the logs. If you're not logged in, there's a button labelled 'Sign in to view logs'.

**Comment by emiltin** [comment]
done, test runs now shown on https://rsmp-nordic.org/compliance/. you need to be logged into github to view the detailed runs, though
